services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my_flask_container
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    volumes:
      - .:/app
    command: flask run --host=0.0.0.0 --port=5000
